### ISSUE TITLE
Can CJS be used for desktop scripting?

### ISSUE THREAD

**Issue by markfilipak** [linuxmint/cjs#65]
How? All I can find is how to build a headless server using nodejs.

Seeking a standard ECMAscript interpreter that has a runtime that allows filesystem access etc. I can't stand BASH.

I've been looking for this for over a year. I've corresponded with folks who say, "Sure, you can do desktop scripting with javascript", then act real coy and won't tell me how.

Thanks for a push in the right direction.

Warm Regards,
Mark.

**Comment by jaszhix** [comment]
Hi Mark, we corresponded over email and I pointed you towards Nodejs since its a more general-purpose environment and has more libraries supporting it, and provided some links to get you started. CJS/GJS isn't a bad choice either, but you will be limited to GNOME-based environments. [This repo](https://github.com/optimisme/gjs-examples) has some good examples showing how you can get started using CJS for that purpose.

**Comment by markfilipak** [comment]
Please don't close this issue. Perhaps someone, some day may be able to help me.

I don't know why you privately send me links to stuff that is so cryptic it is not understandable. Now you give me this link: https://github.com/optimisme/gjs-examples, and it has nothing but links that reload the page...  Are . you . having . fun ?

**Comment by jaszhix** [comment]
Someone can correct me if I'm wrong but the scope of issues here is for CJS running as a component of Cinnamon. 

The links work for me on that repo, its just another Github page. CJS is a fork of GJS, most examples will be for GJS, but they should all work for both projects.

**Comment by markfilipak** [comment]
Well, all the links on this page: 'https://github.com/optimisme/gjs-examples', just reload the page.

https://github.com/optimisme/gjs-examples#gjs-examples
https://github.com/optimisme/gjs-examples#run
https://github.com/optimisme/gjs-examples.git
https://github.com/optimisme/gjs-examples#egassetjs
https://github.com/optimisme/gjs-examples#egiconjs
https://github.com/optimisme/gjs-examples#egcssjs
https://github.com/optimisme/gjs-examples#egjustifyjs
https://github.com/optimisme/gjs-examples#egtimersjs
https://github.com/optimisme/gjs-examples#egeventjs
https://github.com/optimisme/gjs-examples#egspawnjs
https://github.com/optimisme/gjs-examples#eginfojs
https://github.com/optimisme/gjs-examples#egdialogjs
https://github.com/optimisme/gjs-examples#eglistjs
https://github.com/optimisme/gjs-examples#egjsonjs
https://github.com/optimisme/gjs-examples#egopenjs
https://github.com/optimisme/gjs-examples#egheaderjs
https://github.com/optimisme/gjs-examples#egsearchjs
https://github.com/optimisme/gjs-examples#egselectjs
https://github.com/optimisme/gjs-examples#egclutterjs
https://github.com/optimisme/gjs-examples#egcairojs
https://github.com/optimisme/gjs-examples#egwebmsgjs

**Comment by Odyseus** [comment]
Hello, everybody.

@markfilipak: First, you should really learn how to use GitHub because:

1. Those links are *permalinks*. They are supposed to point to the README headers.
2. The files referenced in that README are listed right above the README itself.
3. This repository isn't a support forum. It's here to report issues that you might have with CJS.

And second, stop wasting your time trying to use JavaScript for scripting on your desktop. Use Python (version 3 specifically) and move on. JavaScript should never have *gotten out* of the browser if you ask me.

**Comment by markfilipak** [comment]
Excuse me. The senior people at Linux Mint forums point people to github as though it's a support forum.

I will not trouble you further. Have fun.
